apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - region-labels.yaml

patches:
  - path: gateway-class-key.yaml
  - path: certificate-issuer-key.yaml
  - path: topology-spread-constraints.yaml
  - path: tolerations-taints.yaml

