apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - limitrange.yaml
  - resourcequota.yaml
  - networkpolicy-defaults.yaml

patches:
  - path: dns-config-patch.yaml
  - path: certificate-issuer-key.yaml
  - path: labels-annotations.yaml
  - path: pdb-defaults.yaml
  - path: policy-toggles.yaml

